### ISSUE TITLE
HotSpotImage demo not conform to Euro Quiz demo

### ISSUE THREAD

**Issue by dcabale** [tmssoftware/TMS-Component-Pack-demos#2]
Hello,
the HotSpotImage demo (https://github.com/tmssoftware/TMS-Component-Pack-demos/tree/master/HotSpotImage) is not conform to what is said to be, ie Euro Quiz demo. (https://www.tmssoftware.com/site/img/Hotspotimage_small.png).
-> How can I access to real Euro Quiz demo ?
Thanks

**Comment by BrunoFierens** [comment]
This screenshot is from the FMX HotSpotImage, available in TMS FMX UI Pack
https://www.tmssoftware.com/site/tmsfmxpack.asp
This demo is included in the TMS FMX UI Pack distribution.

**Comment by dcabale** [comment]
Thanks Bruno!
